apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotelfrontend
  namespace: hotel-dev
  labels:
    app: hotel
spec:
  replicas: 2
  selector:
    matchLabels:
      name: hotelfrontend
  template:
    metadata:
      labels:
        name: hotelfrontend
    spec:
      containers:
      - name: 'hotelfrontend'
        image: 'maayanpeleg87/hotel-frontend:latest'
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          readOnlyRootFilesystem: true
        ports:
        - containerPort: 5000
        env:
        - name: 'API_URL'
          value: 'hotelapi'
        - name: 'PORT'
          value: '8000'