version: '3.9'

services:
  db:
    image: 'maayanpeleg87/hotel-db:latest'
    restart: always
    container_name: 'hotel_db'
    ports:
      - '3306:3306'
  api:
    image: 'maayanpeleg87/hotel-api:latest'
    restart: always
    container_name: 'hotel_api'
    ports:
      - '8080:8080'
    depends_on:
      - db
  frontend: 
    image: 'maayanpeleg87/hotel-frontend:latest'
    restart: always
    container_name: 'hotel_frontend'
    ports:
      - '80:5000'
    depends_on:
      - api
  grafana:
    image: 'grafana/grafana:latest'
    container_name: grafana
    ports:
      - '3000:3000' 