apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotelapi
  namespace: hotel-dev
  labels:
    app: hotel
spec:
  replicas: 2
  selector:
    matchLabels:
      name: hotelapi
  template:
    metadata:
      labels:
        name: hotelapi
    spec:
      containers:
      - name: 'hotelapi'
        image: 'maayanpeleg87/hotel-api:latest'
        ports:
        - containerPort: 8000
        env:
        - name: 'DATABASE_URL'
          value: 'hoteldb'
        liveinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        restartPolicy: Always