apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: grafana
  name: grafanaservice
  namespace: devops-tools
spec:
  selector:
    name: grafana
  ports:
  - port: 3000
    targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: devops-tools
  labels:
    app: prometheus
spec:
  selector: 
    name: prometheus
  ports:
  - port: 9090
    targetPort: 9090
